### ISSUE TITLE
Having TypeError: Cannot read properties of undefined (reading 'realHover')

### ISSUE THREAD

**Issue by unirora** [bahmutov/cyclope#85]
I'm having an undefined error when running cypress tests with Cypress version from 11.1.0 to 12.0.2.
Please find the error below,

Because this error occurred during a `before all` hook we are skipping all of the remaining tests.
at $Cypress.eval (webpack:////Users/###/<ProjectName>node_modules/cyclope/src/index.js:12:0)

**Comment by lashchanka** [comment]
➕ Same happened to me.

```tsx
TypeError: Cannot read properties of undefined (reading 'realHover')

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `...`
    at $Cypress.eval (webpack:///./node_modules/cyclope/src/index.js:12:0)
```

@bahmutov , could you, please, maybe try a solution mentioned in this [issue](https://github.com/dmtrKovalenko/cypress-real-events/issues/353#issuecomment-1344593035) as a quick fix?
